# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\":\n\x10TellStoryRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0binstitution\x18\x02 \x01(\t\"\'\n\x11TellStoryResponse\x12\x12\n\ntext_chunk\x18\x01 \x01(\x0c\x32H\n\x10\x41ssistantService\x12\x34\n\tTellStory\x12\x11.TellStoryRequest\x1a\x12.TellStoryResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELLSTORYREQUEST']._serialized_start=19
  _globals['_TELLSTORYREQUEST']._serialized_end=77
  _globals['_TELLSTORYRESPONSE']._serialized_start=79
  _globals['_TELLSTORYRESPONSE']._serialized_end=118
  _globals['_ASSISTANTSERVICE']._serialized_start=120
  _globals['_ASSISTANTSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
